spring.application.name=formacion-polizas

spring.data.mongodb.uri=mongodb+srv://admin:IDI21042d@usuarios.a09qc.mongodb.net/?retryWrites=true&w=majority&appName=Usuarios
spring.data.mongodb.database=usuarios

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoOperations=DEBUG
logging.level.org.mongodb.driver=DEBUG

springdoc.api-docs.path=/swagger-ui.html